/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated.attendance.index'
import { Route as AuthenticatedRoomsIndexRouteImport } from './routes/_authenticated.rooms.index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated.users.index'
import { Route as AuthenticatedWorkshopsIndexRouteImport } from './routes/_authenticated.workshops.index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoomsIndexRoute = AuthenticatedRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkshopsIndexRoute =
  AuthenticatedWorkshopsIndexRouteImport.update({
    id: '/workshops/',
    path: '/workshops/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginRoute
  '/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/rooms/': typeof AuthenticatedRoomsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/workshops/': typeof AuthenticatedWorkshopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/rooms': typeof AuthenticatedRoomsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/workshops': typeof AuthenticatedWorkshopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/_authenticated/rooms/': typeof AuthenticatedRoomsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/workshops/': typeof AuthenticatedWorkshopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/attendance/' | '/rooms/' | '/users/' | '/workshops/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/attendance' | '/rooms' | '/users' | '/workshops'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/login'
    | '/_authenticated/'
    | '/_authenticated/attendance/'
    | '/_authenticated/rooms/'
    | '/_authenticated/users/'
    | '/_authenticated/workshops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms/': {
      id: '/_authenticated/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AuthenticatedRoomsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workshops/': {
      id: '/_authenticated/workshops/'
      path: '/workshops'
      fullPath: '/workshops/'
      preLoaderRoute: typeof AuthenticatedWorkshopsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
  AuthenticatedRoomsIndexRoute: typeof AuthenticatedRoomsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWorkshopsIndexRoute: typeof AuthenticatedWorkshopsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
  AuthenticatedRoomsIndexRoute: AuthenticatedRoomsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWorkshopsIndexRoute: AuthenticatedWorkshopsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
